version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: inventory_postgres

    restart: always

    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: inventory_backend

    restart: always

    depends_on:
      - postgres

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

volumes:
  postgres_data: